# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 08:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tos_rev', models.DateTimeField(null=True, verbose_name='약관 동의')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='단어')),
                ('pos', models.CharField(choices=[('명사', '명사'), ('동사', '동사'), ('형용사', '형용사'), ('부사', '부사'), ('대명사', '대명사'), ('감탄사', '감탄사'), ('관형사', '관형사'), ('특수:금지어', '특수:금지어'), ('특수:파생형', '특수:파생형')], max_length=100, verbose_name='품사')),
                ('props', models.CharField(blank=True, max_length=100, verbose_name='속성')),
                ('stem', models.CharField(blank=True, max_length=100, verbose_name='어근')),
                ('etym', models.CharField(blank=True, max_length=100, verbose_name='어원')),
                ('orig', models.CharField(blank=True, max_length=100, verbose_name='본딧말')),
                ('comment', models.CharField(blank=True, max_length=1000, verbose_name='부가 설명')),
                ('date', models.DateTimeField()),
                ('valid', models.BooleanField(default=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(related_name='editors', to=settings.AUTH_USER_MODEL)),
                ('overrides', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galkwiapp.Entry')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='단어')),
                ('pos', models.CharField(choices=[('명사', '명사'), ('동사', '동사'), ('형용사', '형용사'), ('부사', '부사'), ('대명사', '대명사'), ('감탄사', '감탄사'), ('관형사', '관형사'), ('특수:금지어', '특수:금지어'), ('특수:파생형', '특수:파생형')], max_length=100, verbose_name='품사')),
                ('props', models.CharField(blank=True, max_length=100, verbose_name='속성')),
                ('stem', models.CharField(blank=True, max_length=100, verbose_name='어근')),
                ('etym', models.CharField(blank=True, max_length=100, verbose_name='어원')),
                ('orig', models.CharField(blank=True, max_length=100, verbose_name='본딧말')),
                ('comment', models.CharField(blank=True, max_length=1000, verbose_name='부가 설명')),
                ('date', models.DateTimeField(verbose_name='제안 시각')),
                ('action', models.CharField(choices=[('ADD', '추가'), ('REMOVE', '제거'), ('UPDATE', '변경')], max_length=100, verbose_name='동작')),
                ('rationale', models.CharField(blank=True, max_length=1000, verbose_name='제안 이유')),
                ('status', models.CharField(choices=[('DRAFT', '편집 중'), ('VOTING', '투표 중'), ('CANCELED', '취소'), ('APPROVED', '허용'), ('REJECTED', '거절'), ('EXPIRED', '만료')], max_length=1000)),
                ('status_date', models.DateTimeField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('new_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='making_proposal', to='galkwiapp.Entry')),
                ('old_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removing_proposal', to='galkwiapp.Entry')),
            ],
            options={
                'permissions': [('can_propose', 'Can propose an action')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('vote', models.CharField(choices=[('YES', '예'), ('NO', '아니요')], max_length=1000, verbose_name='찬반')),
                ('reason', models.CharField(blank=True, max_length=1000, verbose_name='이유')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galkwiapp.Proposal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'permissions': [('can_vote', 'Can vote on proposal')],
            },
        ),
    ]
