# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 08:34
from __future__ import unicode_literals

from django.db import migrations, models

def set_old_licenses(apps, schema_editor):
    Revision = apps.get_model('galkwiapp', 'Revision')
    for rev in Revision.objects.all():
        rev.license='MPL-1.1/GPL-2.0/LGPL-2.1'
        rev.save()

class Migration(migrations.Migration):

    dependencies = [
        ('galkwiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='license',
            field=models.CharField(default='CC-BY-4.0', max_length=100, verbose_name='라이선스'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.CharField(choices=[('명사', '명사'), ('동사', '동사'), ('형용사', '형용사'), ('부사', '부사'), ('부사:상태', '부사:상태'), ('부사:성상', '부사:성상'), ('부사:지시', '부사:지시'), ('부사:정도', '부사:정도'), ('부사:부정', '부사:부정'), ('부사:양태', '부사:양태'), ('부사:접속', '부사:접속'), ('대명사', '대명사'), ('감탄사', '감탄사'), ('관형사', '관형사'), ('특수:금지어', '특수:금지어'), ('특수:파생형', '특수:파생형')], max_length=100, verbose_name='품사'),
        ),
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.CharField(choices=[('galkwi', '갈퀴'), ('insighter', '인사이터'), ('sejong', '세종'), ('woorimalsam', '우리말샘')], default='galkwi', max_length=100, verbose_name='원본 사전'),
        ),
        migrations.RunPython(set_old_licenses),
    ]
