# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 04:00
from __future__ import unicode_literals

from django.db import migrations, models

def set_new_pos(apps, schema_editor):
    Word = apps.get_model('galkwiapp', 'Word')
    for word in Word.objects.all():
        pos = word.pos
        props = word.props.split(',')
        if pos == '명사':
            if '가산명사' in props:
                word.pos = '명사:보통:비서술성'
                props.remove('가산명사')
                word.props = ','.join(props)
            elif '고유명사' in props:
                word.pos = '명사:고유'
                props.remove('고유명사')
                word.props = ','.join(props)
            elif '단위명사' in props:
                word.pos = '명사:의존:단위성'
                props.remove('단위명사')
                word.props = ','.join(props)
            elif '의존명사' in props:
                word.pos = '명사:의존:비단위성'
                props.remove('의존명사')
                word.props = ','.join(props)
            else:
                word.pos = '명사:보통:서술성'
                word.props = ','.join(props)
            word.save()

class Migration(migrations.Migration):

    dependencies = [
        ('galkwiapp', '0002_license_20170304_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.CharField(choices=[('명사', '명사'), ('명사:보통:서술성', '명사:보통:서술성'), ('명사:보통:비서술성', '명사:보통:비서술성'), ('명사:고유', '명사:고유'), ('명사:의존:비단위성', '명사:의존:비단위성'), ('명사:의존:단위성', '명사:의존:단위성'), ('동사', '동사'), ('형용사', '형용사'), ('부사', '부사'), ('부사:상태', '부사:상태'), ('부사:성상', '부사:성상'), ('부사:지시', '부사:지시'), ('부사:정도', '부사:정도'), ('부사:부정', '부사:부정'), ('부사:양태', '부사:양태'), ('부사:접속', '부사:접속'), ('대명사', '대명사'), ('감탄사', '감탄사'), ('관형사', '관형사'), ('특수:금지어', '특수:금지어'), ('특수:파생형', '특수:파생형')], max_length=100, verbose_name='품사'),
        ),
        migrations.RunPython(set_new_pos),
    ]
